version: '3.9'

services:
  db:
    container_name: postgres_db
    ports:
      - "5432:5432"
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root