name: Deployment Pipeline
on:
  push:
    branches:
      - main
      - develop
      - chore/**

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
          - uses: pnpm/action-setup@v2
            with:
              version: 6.0.2

    node:
        needs: install
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                    fetch-depth: 0
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
            - name: Check files
              run: "ls -la"
            - name: Install dependencies
              run: "pnpm i"
            - name: Upload files
              uses: actions/upload-artifact@v2
              with:
                    name: files
                    path: ./
    lint:
        needs: node
        runs-on: ubuntu-20.04
        steps:
            - name: Download files
              uses: actions/download-artifact@v2
              with:
                    name: files
                    path: ./
            - name: Prettify
              run: "npx prettier --write ."
            - name: Lint
              run: "npm run lint --fix ."
    
    
