name: Deployment Pipeline

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node with pnpm
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: 18
          args: --frozen-lockfile
      - name: Check files
        run: 'ls -la'
      - name: Lint
        run: 'npm run lint --fix .'
  build:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node with pnpm
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: 18
          args: --frozen-lockfile
      - name: Build
        run: 'tsc -outDir dist'
  notify:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: fateyan/action-discord-notifier@v1
        with:
          message-title: New Commits Pushed
          webhook: https://canary.discord.com/api/webhooks/1131340717827031180/j1breMDa3JBzZ_BrXQZNqOwxQgG8cxiXbIz2g5JOpnmihmoQH7-jr0H_PiDvdP2dcdXm
