name: Deployment Pipeline
on:
  push:
    branches:
      - main
      - develop
      - chore/**

jobs:
    lint:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                    fetch-depth: 0
            - name: Setup Node with pnpm
              uses: NullVoxPopuli/action-setup-pnpm@v2
              with:
                    node-version: 18
                    args: --frozen-lockfile
            # - name: Install dependencies
            #   run: "pnpm install"
            - name: Check files
              run: "ls -la"
            - name: Lint
              run: "npm run lint --fix ."
    
    